add back config_check yml_dns_check in clashwrt.sh and add debug log in other sciprts

diff --git a/luci-app-clashwrt/root/etc/init.d/clashwrt b/luci-app-clashwrt/root/etc/init.d/clashwrt
--- a/luci-app-clashwrt/root/etc/init.d/clashwrt
+++ b/luci-app-clashwrt/root/etc/init.d/clashwrt
@@ -9,23 +9,25 @@ STOP=15
 . $IPKG_INSTROOT/usr/share/clashwrt/log.sh
 
 [ -f /etc/openwrt_release ] && {
-   RAW_CONFIG_FILE=$(uci -q get openclash.config.config_path)
+   RAW_CONFIG_FILE=$(uci -q get clashwrt.config.config_path)
    CONFIG_FILE="/etc/clashwrt/$(uci -q get clashwrt.config.config_path |awk -F '/' '{print $5}' 2>/dev/null)"
 }
 LOGTIME=$(echo $(date "+%Y-%m-%d %H:%M:%S"))
 CLASH="/etc/clashwrt/clash"
 CLASH_CONFIG="/etc/clashwrt"
 CRON_FILE="/etc/crontabs/root"
-
+DNS_FILE="/tmp/yaml_dns.yaml"
 LOG_FILE="/tmp/clashwrt.log"
 START_LOG="/tmp/clashwrt_start.log"
 LOCK_FILE=/tmp/lock/clashwrt.lock
 PROXY_FWMARK="0x162"
 PROXY_ROUTE_TABLE="0x162"
 
+
 if [ ! -f "/etc/clashwrt/clash" ]; then
-    ln -s /etc/clashwrt/core/clash_tun /etc/clashwrt/clash 2>/dev/null
+    ln -s /etc/clashwrt/core/clash_tun /etc/clashwrt/clash 2>>"$DEBUG_LOG"
 fi
+
 
 set_lock() {
    exec 888>"$LOCK_FILE" 2>/dev/null
@@ -53,6 +55,58 @@ start_fail()
    exit 0
 }
 
+config_check()
+{
+#创建启动配置
+#rm -rf "/etc/openclash/*.y*" 2>/dev/null
+cp "$RAW_CONFIG_FILE" "$CONFIG_FILE"
+
+ruby -ryaml -E UTF-8 -e "
+begin
+   YAML.load_file('$RAW_CONFIG_FILE');
+rescue Exception => e
+   puts '${LOGTIME} Error: Unable To Parse Config File,【' + e.message + '】'
+   system 'rm -rf ${CONFIG_FILE}'
+end
+" 2>/dev/null >> $LOG_FILE
+if [ $? -ne 0 ]; then
+   LOG_OUT "Error: Ruby Works Abnormally, Please Check The Ruby Library Depends!"
+   sleep 3
+   start_fail
+elif [ ! -f "$CONFIG_FILE" ] || [ ! -s "$CONFIG_FILE" ]; then
+   LOG_OUT "Error: Config File Format Validation Failed..."
+   sleep 3
+   start_fail
+fi
+
+#检查field名称（不兼容旧写法）
+ruby -ryaml -E UTF-8 -e "
+   Value = YAML.load_file('$CONFIG_FILE');
+   if Value.key?('Proxy') or Value.key?('Proxy Group') or Value.key?('Rule') or Value.key?('rule-provider') then
+      if Value.key?('Proxy') then
+         Value['proxies'] = Value['Proxy']
+         Value.delete('Proxy')
+         puts '${LOGTIME} Warning: Proxy is no longer used. Auto replaced by proxies'
+      end
+      if Value.key?('Proxy Group') then
+         Value['proxy-groups'] = Value['Proxy Group']
+         Value.delete('Proxy Group')
+         puts '${LOGTIME} Warning: Proxy Group is no longer used. Auto replaced by proxy-groups'
+      end
+      if Value.key?('Rule') then
+         Value['rules'] = Value['Rule']
+         Value.delete('Rule')
+         puts '${LOGTIME} Warning: Rule is no longer used. Auto replaced by rules'
+      end
+      if Value.key?('rule-provider') then
+         Value['rule-providers'] = Value['rule-provider']
+         Value.delete('rule-provider')
+         puts '${LOGTIME} Warning: rule-provider is no longer used. Auto replaced by rule-providers'
+      end;
+      File.open('$CONFIG_FILE','w') {|f| YAML.dump(Value, f)};
+   end;
+   " 2>/dev/null >> $LOG_FILE
+}
 
 # #配置文件选择
 config_choose()
@@ -175,23 +229,23 @@ start_run_core()
    # else
    kill_clash
    if [ -z "$_koolshare" ]; then
+      LOG_OUT "KOOLSHARE -Z=", "$_koolshare"
       #防止赋权失败
       touch "/tmp/clashwrt.log" 2>/dev/null
       # chmod o+w /etc/openclash/proxy_provider/* 2>/dev/null
       # chmod o+w /etc/openclash/rule_provider/* 2>/dev/null
       chmod o+w /tmp/clashwrt.log 2>/dev/null
-      chown nobody:nogroup /etc/openclash/core/* 2>/dev/null
+      chown nobody:nogroup /etc/clashwrt/core/* 2>/dev/null
       #使用nobody启动内核方便代理路由自身流量
       capabilties="cap_sys_resource,cap_dac_override,cap_net_raw,cap_net_bind_service,cap_net_admin"
       capsh --caps="${capabilties}+eip" -- -c "capsh --user=nobody --addamb='${capabilties}' -- -c 'nohup $CLASH -d $CLASH_CONFIG -f \"$CONFIG_FILE\" >> $LOG_FILE 2>&1 &'" >> $LOG_FILE 2>&1
    else
+      LOG_OUT "KOOLSHARE -NOTZ=", "$_koolshare"
       nohup $CLASH -d $CLASH_CONFIG -f "$CONFIG_FILE" >> $LOG_FILE 2>&1 &
    fi
    # uci -q set openclash.config.config_reload=1
    # uci -q commit openclash
 }
-
-
 
 check_core_status()
 {
@@ -203,6 +257,71 @@ check_core_status()
    done
    if [ -z "$(pidof clash)" ]; then
       LOG_ALERT
+   fi
+}
+
+yml_dns_check()
+{
+   #检查DNS服务
+   if [ -z "$(ruby_read "$1" "['dns']['nameserver']")" ]; then
+      LOG_OUT "Detected That The nameserver DNS Option Has No Server Set, Starting To Complete..."
+      echo "  nameserver:" > "$DNS_FILE" 2>/dev/null
+      cat >> "$DNS_FILE" <<-EOF
+    - 114.114.114.114
+    - 119.29.29.29
+    - 223.5.5.5
+  fallback:
+    - https://dns.cloudflare.com/dns-query
+    - https://public.dns.iij.jp/dns-query
+    - https://jp.tiar.app/dns-query
+    - https://jp.tiarap.org/dns-query
+    - tls://dot.tiar.app
+EOF
+      if [ -z "$(ruby_read "$1" "['dns']")" ]; then
+         ruby_cover "$1" "['dns']" "$DNS_FILE"
+      else
+         ruby_merge "$1" "['dns']" "$DNS_FILE"
+      fi
+   fi
+   
+   #default-nameserver
+   ruby -ryaml -E UTF-8 -e "
+   begin
+      Value = YAML.load_file('$1');
+      reg = /^((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.){3}(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])(?::(?:[0-9]|[1-9][0-9]{1,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5]))?$/;
+      reg6 = /^(?:(?:(?:[0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}((\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b)\.){3}(\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b))|(([0-9A-Fa-f]{1,4}:){0,5}:((\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b)\.){3}(\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b))|(::([0-9A-Fa-f]{1,4}:){0,5}((\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b)\.){3}(\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:))|\[(?:(?:(?:[0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}:[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){5}:([0-9A-Fa-f]{1,4}:)?[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){4}:([0-9A-Fa-f]{1,4}:){0,2}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){3}:([0-9A-Fa-f]{1,4}:){0,3}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){2}:([0-9A-Fa-f]{1,4}:){0,4}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){6}((\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b)\.){3}(\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b))|(([0-9A-Fa-f]{1,4}:){0,5}:((\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b)\.){3}(\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b))|(::([0-9A-Fa-f]{1,4}:){0,5}((\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b)\.){3}(\b((25[0-5])|(1\d{2})|(2[0-4]\d)|(\d{1,2}))\b))|([0-9A-Fa-f]{1,4}::([0-9A-Fa-f]{1,4}:){0,5}[0-9A-Fa-f]{1,4})|(::([0-9A-Fa-f]{1,4}:){0,6}[0-9A-Fa-f]{1,4})|(([0-9A-Fa-f]{1,4}:){1,7}:))\](?::(?:[0-9]|[1-9][0-9]{1,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5]))?$/i;
+      if Value['dns'].has_key?('fallback') then
+         Value_1=Value['dns']['nameserver'] | Value['dns']['fallback']
+      else
+         Value_1=Value['dns']['nameserver']
+      end;
+      Value_1.each{|x|
+         if x =~ reg or x =~ reg6 then
+            if Value['dns'].has_key?('default-nameserver') then
+               Value['dns']['default-nameserver']=Value['dns']['default-nameserver'].to_a.insert(-1,x).uniq
+            else
+               Value_2={'default-nameserver'=>[x]}
+               Value['dns'].merge!(Value_2)
+            end
+         end
+       };
+       File.open('${1}','w') {|f| YAML.dump(Value, f)};
+    rescue Exception => e
+    puts '${LOGTIME} Error: Set default-nameserver Error,【' + e.message + '】'
+    end
+    " 2>/dev/null >> $LOG_FILE
+   
+   #fallback-filter
+   if [ "$custom_fallback_filter" = "1" ]; then
+      if [ -z "$(ruby_read "$CONFIG_FILE" "['dns']['fallback']")" ]; then
+         LOG_OUT "Error: Fallback-Filter Need fallback of DNS Been Setted, Ignore..."
+         return
+      fi
+      if [ -z "$(ruby_read "$2" "['fallback-filter']")" ]; then
+         LOG_OUT "Error: Unable To Parse Custom Fallback-Filter File, Ignore..."
+         return
+      fi
+      ruby_merge "$CONFIG_FILE" "['dns']" "$2"
    fi
 }
 
@@ -421,26 +540,26 @@ check_core_status()
 set_firewall()
 {
 
-if [ -z "$(uci -q get firewall.clashwrt)" ] || [ -z "$(uci -q get ucitrack.@openclash[-1].init)" ]; then
-   uci -q delete ucitrack.@openclash[-1]
-   uci -q add ucitrack openclash
-   uci -q set ucitrack.@openclash[-1].init=openclash
+if [ -z "$(uci -q get firewall.clashwrt)" ] || [ -z "$(uci -q get ucitrack.@clashwrt[-1].init)" ]; then
+   uci -q delete ucitrack.@clashwrt[-1]
+   uci -q add ucitrack clashwrt
+   uci -q set ucitrack.@clashwrt[-1].init=clashwrt
    uci -q commit ucitrack
-   uci -q delete firewall.openclash
-   uci -q set firewall.openclash=include
-   uci -q set firewall.openclash.type=script
-   uci -q set firewall.openclash.path=/var/etc/openclash.include
-   uci -q set firewall.openclash.reload=1
+   uci -q delete firewall.clashwrt
+   uci -q set firewall.clashwrt=include
+   uci -q set firewall.clashwrt.type=script
+   uci -q set firewall.clashwrt.path=/var/etc/clashwrt.include
+   uci -q set firewall.clashwrt.reload=1
 fi
 
 mkdir -p /var/etc
-cat > "/var/etc/openclash.include" <<-EOF
-/etc/init.d/openclash reload >/dev/null 2>&1
+cat > "/var/etc/clashwrt.include" <<-EOF
+/etc/init.d/clashwrt reload >/dev/null 2>&1
 EOF
 
 if [ "$china_ip_route" = "1" ] || [ "$disable_udp_quic" = "1" ]; then
    ipset -! flush china_ip_route 2>/dev/null
-   ipset -! restore </etc/openclash/china_ip_route.ipset 2>/dev/null
+   ipset -! restore </etc/clashwrt/china_ip_route.ipset 2>/dev/null
 fi
 
 if [ "$enable_redirect_dns" -eq 1 ] && [ -z "$(iptables -t nat -nL PREROUTING --line-number |grep 'DNS Hijack')"]; then
@@ -942,8 +1061,9 @@ start()
    # if ! $quick_start; then
    LOG_OUT "Step 3: Modify The Config File..."
    LOG_OUT "$en_mode|$da_password|$cn_port|$proxy_port|$CONFIG_FILE|$ipv6_enable|$http_port|$socks_port|$log_level|$proxy_mode|$en_mode_tun|$stack_type|$dns_port|$mixed_port|$tproxy_port|$ipv6_dns|$store_fakeip|$stream_domains_prefetch|$dns_remote"
+   config_check
    /usr/share/clashwrt/yml_change.sh 2>/dev/null "$en_mode" "$da_password" "$cn_port" "$proxy_port" "$CONFIG_FILE" "$ipv6_enable" "$http_port" "$socks_port" "$log_level" "$proxy_mode" "$en_mode_tun" "$stack_type" "$dns_port" "$mixed_port" "$tproxy_port" "$ipv6_dns" "$store_fakeip" "$stream_domains_prefetch" "$dns_remote"
-
+   yml_dns_check "$CONFIG_FILE"  "$FALLBACK_FILTER_FILE"
    #    config_check
    #    # config_load "openclash"
    #    config_foreach yml_auth_get "authentication"
@@ -956,7 +1076,7 @@ start()
    #    yml_provider_path "$CONFIG_FILE" "proxy-providers" "proxy_provider"
    #    yml_provider_path "$CONFIG_FILE" "rule-providers" "rule_provider"
    #    yml_vmess_compatible "$CONFIG_FILE" "proxies"
-   #    yml_dns_check "$CONFIG_FILE"  "$FALLBACK_FILTER_FILE"
+   # yml_dns_check "$CONFIG_FILE"  "$FALLBACK_FILTER_FILE"
    #    yml_tolerance_set "$CONFIG_FILE" "$tolerance"
    # fi
    
@@ -972,31 +1092,31 @@ start()
    # yml_provider_check "$CONFIG_FILE" "rule-providers" "payload"
    # try_restore_start
 
-   LOG_OUT "Step 7: Set Control Panel..."
-   ln -s /usr/share/openclash/yacd /www/luci-static/openclash 2>/dev/null
+   # LOG_OUT "Step 7: Set Control Panel..."
+   # ln -s /usr/share/openclash/yacd /www/luci-static/openclash 2>/dev/null
        
    LOG_OUT "Step 8: Set Firewall Rules..."
    set_firewall
 
    LOG_OUT "Step 9: Restart Dnsmasq..."
    change_dns "$enable_redirect_dns" "$disable_masq_cache"
-   /etc/init.d/dnsmasq restart >/dev/null 2>&1
+   /etc/init.d/dnsmasq restart >>"$DEBUG_LOG" 2>&1
    
-   LOG_OUT "Step 10: Add Cron Rules, Start Daemons..."
-   add_cron
-   if [ -z "$(uci -q get dhcp.lan.dhcpv6)" ] && [ "$(uci -q get openclash.config.restricted_mode)" != "1" ]; then
-      LOG_OUT "OpenClash Start Successful!"
-      sleep 3
-   elif [ -n "$(uci -q get dhcp.lan.dhcpv6)" ] && [ "$ipv6_enable" -eq 0 ]; then
-      LOG_OUT "Warning: OpenClash Start Successful, Please Note That Network May Abnormal With IPv6's DHCP Server"
-      sleep 3
-   fi
-   if [ "$(uci -q get openclash.config.restricted_mode)" = "1" ]; then
-      LOG_OUT "Warning: OpenClash Start Successful With Raw Config File, Please Note That It's Restricted Mode Now"
-      sleep 3
-   fi
-   echo "OpenClash Already Start!"
-   write_run_quick
+   # LOG_OUT "Step 10: Add Cron Rules, Start Daemons..."
+   # add_cron
+   # if [ -z "$(uci -q get dhcp.lan.dhcpv6)" ] && [ "$(uci -q get openclash.config.restricted_mode)" != "1" ]; then
+   #    LOG_OUT "OpenClash Start Successful!"
+   #    sleep 3
+   # elif [ -n "$(uci -q get dhcp.lan.dhcpv6)" ] && [ "$ipv6_enable" -eq 0 ]; then
+   #    LOG_OUT "Warning: OpenClash Start Successful, Please Note That Network May Abnormal With IPv6's DHCP Server"
+   #    sleep 3
+   # fi
+   # if [ "$(uci -q get openclash.config.restricted_mode)" = "1" ]; then
+   #    LOG_OUT "Warning: OpenClash Start Successful With Raw Config File, Please Note That It's Restricted Mode Now"
+   #    sleep 3
+   # fi
+   # echo "OpenClash Already Start!"
+   # write_run_quick
    SLOG_CLEAN
    rm -rf /tmp/yaml_*
 }
@@ -1036,7 +1156,7 @@ stop()
    redirect_dns=$(uci -q get clashwrt.config.redirect_dns)
    masq_cache=$(uci -q get clashwrt.config.masq_cache)
    default_resolvfile=$(uci -q get clashwrt.config.default_resolvfile)
-   revert_dns "$redirect_dns" "$masq_cache" "$dns_port" "$enable" "$default_resolvfile"
+   # revert_dns "$redirect_dns" "$masq_cache" "$dns_port" "$enable" "$default_resolvfile"
    /etc/init.d/dnsmasq restart >/dev/null 2>&1
 
    LOG_OUT "Step 6: Delete OpenClash Residue File..."
@@ -1058,7 +1178,7 @@ stop()
       rm -rf $LOG_FILE
    fi
    
-   del_cron
+   # del_cron
    rm -rf /tmp/yaml_*
    rm -rf $START_LOG
    echo "ClashWRT Already Stop!"
@@ -1071,7 +1191,7 @@ restart()
    mkdir -p /tmp/lock
    touch $LOCK_FILE
    set_lock
-   stop
+   # stop
    start
    del_lock
 }
